# Generated by Django 5.2.15 on 2026-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_bio_profile_bio_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='status_en',
        ),
        migrations.AddField(
            model_name='profile',
            name='status_fa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
