# Generated by Django 6.0.7 on 2026-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
