# Generated by Django 6.0.7 on 2026-08-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_blogpost_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
    ]
