# Generated by Django 6.0.7 on 2026-08-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_content_blogpost_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='platform',
        ),
    ]
