# Generated by Django 6.0.7 on 2026-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_blogpost_content_blogpost_slug_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
