# Generated by Django 6.0.7 on 2026-09-02 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_en_highlight',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
