# Generated by Django 6.0.7 on 2026-09-02 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_profile_name_en_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_login',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
