# Generated by Django 6.0.7 on 2026-09-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_profile_bio_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_en_highlight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_en',
        ),
        migrations.AddField(
            model_name='profile',
            name='status_login',
            field=models.TextField(blank=True),
        ),
    ]
